### ISSUE TITLE
Disable proxy for explicit application

### ISSUE THREAD

**Issue by chonlon** [SukkaW/zsh-proxy#13]
Q: How to disable the proxy for a special program now, such as yarn.
Env: manjaro

**Comment by SukkaW** [comment]
Currently, it is impossible to prevent a specific program from being applied. Besides, `yarn` does respect `HTTPS_PROXY` and `HTTP_PROXY` in the environment variable anyway, so you should use `noproxy` directly to temporarily disable all proxy.
