### ISSUE TITLE
curl -s -k https://api-ipv4.ip.sb/ip returns "403 Forbidden"

### ISSUE THREAD

**Issue by nklkarthi** [SukkaW/zsh-proxy#18]
curl -s -k https://api-ipv4.ip.sb/ip returns "403 Forbidden" since 2 weeks. If the user-agent is added, then it returns the correct IP

**Comment by SukkaW** [comment]
> curl -s -k https://api-ipv4.ip.sb/ip returns "403 Forbidden" since 2 weeks. If the user-agent is added, then it returns the correct IP

Duplicate as https://github.com/SukkaW/zsh-proxy/issues/15 and has been fixed in https://github.com/SukkaW/zsh-proxy/pull/16. Just update the plugin and it will work again.
