### ISSUE TITLE
The vite project started by npm run dev does not go through the clash proxy

### ISSUE THREAD

**Issue by tlerbao** [SukkaW/zsh-proxy#28]
I use Clash as a proxy software and have configured *.test to point to 127.0.0.1.

In my Vue 3 Vite project, server.proxy is set to redirect /api to xxx.test.

Even after starting the proxy using npm run dev, the frontend project is still unable to access xxx.test.

What could be the reason for this?

<img width="529" alt="CleanShot 2023-11-01 at 22 58 40@2x" src="https://github.com/SukkaW/zsh-proxy/assets/20442232/f3b1b4ba-fcb7-4fd3-89a4-78e9deb4835f">

**Comment by SukkaW** [comment]
Vite doesn't use [`http-proxy-agent`](https://www.npmjs.com/package/http-proxy-agent) in the implementation of `server.proxy`. 

You should report the issue to the Vite. You can also switch to webpack.

**Comment by tlerbao** [comment]
![CleanShot 2023-11-05 at 17 43 22@2x](https://github.com/SukkaW/zsh-proxy/assets/20442232/50950853-4655-43c5-b42c-6a32e8f22a5e)


@SukkaW
