### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by mouyase** [SukkaW/zsh-proxy#3]
![image](https://user-images.githubusercontent.com/7844572/83491843-f8aff000-a4e4-11ea-92e1-9ef22511eca4.png)

**Comment by imrickywong** [comment]
turn `curl -s ...` to `curl -s -k ...`  in `zsh-proxy.plugin.zsh`

**Comment by SukkaW** [comment]
> turn `curl -s ...` to `curl -s -k ...` in `zsh-proxy.plugin.zsh`

@imrickywong Would you like to open a new PR to fix this?

**Comment by mouyase** [comment]
@SukkaW look my PR, I fixed it.

**Comment by septs** [comment]
@SukkaW merged
